### ISSUE TITLE
Signing IPA stucks at 75%

### ISSUE THREAD

**Issue by RudeBoy4RomUA** [DebianArch64/DebProvision#193] opened 2023-10-19 20:00 UTC
I tried to install multiple apps on my iphone 7, latest update. All of them got stuck on 75% and 60%
I tried to sign retroarch, delta emulator, and other apps - all of them stuck at certain %, and nothing happens.  Console says: redirecting to MUX

**Comment by RudeBoy4RomUA** [comment] 2023-10-19 20:36
Ok, It works with VPN - actually idk why that works, for me and others, but it just works. I wont promote any vpn apps, I guess you can use whatever you like.

**Comment by DebianArch64** [comment] 2023-11-17 17:35
This is a duplicate of #187 , what happens is ScarletCloud uses an experimental trick to loopback the computers usbmuxd socket to the phone so that all features can remain the same no matter the type of connection but it introduced a bug

Wireguard only exposes the usbmuxd socket on the phone to another address the phone can contact, no servers are involved

**Closed by DebianArch64** 2023-11-17 17:35 UTC
