### ISSUE TITLE
Scarlet not installing 

### ISSUE THREAD

**Issue by macfixs** [DebianArch64/DebProvision#153] opened 2023-06-01 20:43 UTC
When i install scarlet on macOS it gives me this message:     error failed installing scarlet:recive packet:ApplicationVerificationFailed(failed to verify code signature of/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.kmr3SU/extracted/payload/scarlet.app:0xe8008015(A valid provisining profile for this executable was not found.)) 

Does anyone know how to fix?

**Comment by the1prodigy** [comment] 2023-06-02 18:40
![Uploading Screenshot 2023-06-02 at 20.18.34.png…]()

**Comment by MEhdimmz** [comment] 2023-06-04 22:32
same problem on macOS

>>> Can't Load P12 or PrivateKey File! Please Input The Correct File And Password!

**Comment by heyimdumblol** [comment] 2023-06-07 11:57
I've got the same problem

**Comment by DebianArch64** [comment] 2023-07-07 13:29
Duplicate of #150

**Closed by DebianArch64** 2023-07-07 13:29 UTC
