### ISSUE TITLE
Unable To Refresh Any App Except Scarlet

### ISSUE THREAD

**Issue by gharshit606** [DebianArch64/DebProvision#65] opened 2022-11-29 14:22 UTC
As you said to update the scarlet app, I did and it fix the duplication bug and scarlet refresh bug. But now there is one another bug occurred. We are unable to Refresh any other app rather than scarlet. It gives an error “failed to load info.plist” while refreshing and if we try to refresh again just after that error then it gives another error “failed to create installation proxy”. All we can do is to uninstall the sideloaded app and install it again which also removes the data of app. Methods like turning on/off wireguard emp then reopening scarlet app or turning on/off wifi fixes the issues for the errors while sideloading the app or refreshing the scarlet app itself. But error still persist if we refresh other sideloaded apps even after trying all the above mentioned methods. Do you have any fix for that?

**Comment by DebianArch64** [comment] 2022-11-29 14:27
> 

Issue probably was caused by the previous Scarlet update you had. Pretty much the old Scarlet update used to delete the backup of the app and that's the cause for not getting a prompt

^^^ if this isn't what's happening then I'll definitely look into it when I get home

**Comment by gharshit606** [comment] 2022-11-30 08:07
> Issue probably was caused by the previous Scarlet update you had. Pretty much the old Scarlet update used to delete the backup of the app and that's the cause for not getting a prompt - fix is re-sideloading the app no app deletion necessary that will allow app refresh from that point on
> 
> ^^^ if this isn't what's happening then I'll definitely look into it when I get home

I re-sideloaded the app without deleting it, and at 66% it gives me the same error “failed to load info.plist”. It only working when i delete the sideloaded app and then sideload it again, and as i said this will delete its data too. Moreover, I tried this on both of the scarlet version the latest one and the previous one scarletcloudGUI. Both have same errors.

**Comment by DebianArch64** [comment] 2022-12-23 00:05
> > Issue probably was caused by the previous Scarlet update you had. Pretty much the old Scarlet update used to delete the backup of the app and that's the cause for not getting a prompt - fix is re-sideloading the app no app deletion necessary that will allow app refresh from that point on
> > ^^^ if this isn't what's happening then I'll definitely look into it when I get home
> 
> I re-sideloaded the app without deleting it, and at 66% it gives me the same error “failed to load info.plist”. It only working when i delete the sideloaded app and then sideload it again, and as i said this will delete its data too. Moreover, I tried this on both of the scarlet version the latest one and the previous one scarletcloudGUI. Both have same errors.

Info.plist and other refresh issues are officially fixed now

**Closed by DebianArch64** 2022-12-23 00:05 UTC
