### ISSUE TITLE
app download issue, any app downloading stays stuck at 25%

### ISSUE THREAD

**Issue by owlw** [DebianArch64/DebProvision#89] opened 2022-12-28 02:05 UTC

**Comment by owlw** [comment] 2022-12-28 02:05
title says it all

**Comment by DebianArch64** [comment] 2022-12-28 02:53
> title says it all

Is the Scarlet and ScarletCloud you are using up-to-date? Earlier today a faulty Scarlet build was pushed

**Comment by owlw** [comment] 2022-12-28 14:29
> > title says it all
> 
> 
> 
> Is the Scarlet and ScarletCloud you are using up-to-date? Earlier today a faulty Scarlet build was pushed

i was using the gui release version

**Comment by owlw** [comment] 2022-12-28 14:30
the one from may 2022

**Comment by owlw** [comment] 2022-12-28 15:26
![image](https://user-images.githubusercontent.com/68487112/209834338-65ac5ae9-2f29-4231-adc3-2db5a417a5b1.png)

This is the build from 20 hours ago. In this screenshot im downloading iSpooferX and it stays stuck like this. The same thing happens with every app.

**Comment by DebianArch64** [comment] 2022-12-28 16:45
> ![image](https://user-images.githubusercontent.com/68487112/209834338-65ac5ae9-2f29-4231-adc3-2db5a417a5b1.png)
> 
> This is the build from 20 hours ago. In this screenshot im downloading iSpooferX and it stays stuck like this. The same thing happens with every app.

I spot the cause it happens under a certain circumstance. I'll be pushing a fix today and will close this comment when it releases

**Comment by DebianArch64** [comment] 2022-12-28 18:18
This issue is now fully fixed. Speed and stability improvements for login was also made

You can update by clicking "Install Scarlet" from ScarletCloud

**Closed by DebianArch64** 2022-12-28 18:18 UTC

**Comment by wesselvdv** [comment] 2023-06-18 08:23
I am having the same symptoms as this issue. Every app I try to install stays stuck at 25%.
